export const products = [
  {
    id: 1,
    name: "Esmalte Premium",
    brand: 'Cintoplom',
    slug: "esmalte-premium",
    category: 'Esmalte',
    color: "bg-orange-400",
    img: "https://res.cloudinary.com/dbgt948uj/image/upload/v1760642488/CintoplomLatexMASTER__2_-removebg-preview_qdwqen.png",
    label: "Membrana Poliuretano",
    labelColor: "bg-orange-500",
        format: [
      "10L",
      "20L",
    ],
  },
  {
    id: 2,
    name: "Membrana Poliuretano",
    category: 'Membrana',
    brand: 'Cintoflex',
    slug: "membrana-poliuretano",
    format: [
      "10L",
      "20L",
    ],
    color: "bg-yellow-500",
    img: "https://res.cloudinary.com/dbgt948uj/image/upload/v1760641127/CintoflexMASTERfrentes__3_-removebg-preview_hxrdjk.png",
    label: "Membrana Poliuretano",
    labelColor: "bg-yellow-500",
  },
  {
    id: 3,
    name: "Latex Interior/Exterior",
    brand: 'Cintotex',
      category: 'Latex',
    slug: "latex-interior-exterior",
    color: "bg-zinc-800",
    label: "Latex lavable interior y exterior",
    img: "https://res.cloudinary.com/dbgt948uj/image/upload/v1760642549/CintotexMASTER__4_-removebg-preview_txvahx.png",
    labelColor: "bg-zinc-800",
        format: [
      "10L",
      "20L",
    ],
  },
  {
    id: 4,
    name: "Esmalte Sintético",
    brand: 'Cintoflex',
    category: 'Esmalte',
    slug: "esmalte-sintetico",
    color: "bg-yellow-500",
    img: "https://res.cloudinary.com/dbgt948uj/image/upload/v1760642630/CintoflexMASTERtechos__1_-removebg-preview_z58bmv.png",
    label: "Membrana Poliuretano",
    labelColor: "bg-yellow-500",
        format: [
      "10L",
      "20L",
    ],
  },
  {
    id: 5,
    name: "Pintura Amarilla",
    slug: "pintura-amarilla",
    category: 'Latex',
    brand: 'Cintoflex',
    color: "bg-blue-500",
    img: "https://res.cloudinary.com/dbgt948uj/image/upload/v1760642786/CintoplomULTRAlatex__4_-removebg-preview_hvsjer.png",
    label: "Latex lavable interior y exterior",
    labelColor: "bg-blue-500",
        format: [
      "1L",
      '10L'
    ],
  },
];
